// A.1 [EF.Migrations] Schema change: Events.ResponsibleUserId.
// What: Adds the ResponsibleUserId column so each booking can be owned by a contributor.
// Why: Ownership enables permission checks (edit/delete) and is the key for monthly payment calculation.
// Where: Generated by `dotnet ef migrations add AddEventResponsibleUserId` and applied at startup via Database.MigrateAsync() in Program.cs.
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace API.Migrations
{
    /// <inheritdoc />
    public partial class AddEventResponsibleUserId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ResponsibleUserId",
                table: "Events",
                type: "TEXT",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ResponsibleUserId",
                table: "Events");
        }
    }
}
