// A.1 [EF.Migrations] Schema change: ContributorPayments table.
// What: Adds the ContributorPayments table + unique index used for persisted monthly payment history.
// Why: Supports an auditable "ledger" view for contributors (shown in #/portal/me).
// Where: Generated by `dotnet ef migrations add AddContributorPayments` and applied at startup via Database.MigrateAsync() in Program.cs.
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace API.Migrations
{
    /// <inheritdoc />
    public partial class AddContributorPayments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ContributorPayments",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    UserId = table.Column<string>(type: "TEXT", nullable: false),
                    PeriodYear = table.Column<int>(type: "INTEGER", nullable: false),
                    PeriodMonth = table.Column<int>(type: "INTEGER", nullable: false),
                    TotalMinutes = table.Column<int>(type: "INTEGER", nullable: false),
                    HourlyRate = table.Column<decimal>(type: "TEXT", nullable: false),
                    BaseAmount = table.Column<decimal>(type: "TEXT", nullable: false),
                    EventCount = table.Column<int>(type: "INTEGER", nullable: false),
                    EventBonusAmount = table.Column<decimal>(type: "TEXT", nullable: false),
                    Subtotal = table.Column<decimal>(type: "TEXT", nullable: false),
                    VatRate = table.Column<decimal>(type: "TEXT", nullable: false),
                    VatAmount = table.Column<decimal>(type: "TEXT", nullable: false),
                    TotalIncludingVat = table.Column<decimal>(type: "TEXT", nullable: false),
                    CalculatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ContributorPayments", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ContributorPayments_PeriodYear_PeriodMonth_UserId",
                table: "ContributorPayments",
                columns: new[] { "PeriodYear", "PeriodMonth", "UserId" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ContributorPayments");
        }
    }
}
